// <auto-generated />
using System;
using AccesoDatos.RepositorioEntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccesoDatos.Migrations
{
    [DbContext(typeof(HistoriasContext))]
    [Migration("20260910115250_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Entidades.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdministradorId")
                        .HasColumnType("int");

                    b.Property<int?>("CapituloId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("HistoriaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("CapituloId");

                    b.HasIndex("HistoriaId");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("Dominio.Entidades.Capitulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("HistoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HistoriaId");

                    b.ToTable("Capitulos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Capitulo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Dominio.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HistoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HistoriaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Dominio.Entidades.Historia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapituloInicialId")
                        .HasColumnType("int");

                    b.Property<int?>("CapituloInicialId1")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CapituloInicialId1");

                    b.ToTable("Historias");
                });

            modelBuilder.Entity("Dominio.Entidades.Lectura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FinalAlcanzadoId")
                        .HasColumnType("int");

                    b.Property<int>("HistoriaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FinalAlcanzadoId");

                    b.HasIndex("HistoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Lecturas");
                });

            modelBuilder.Entity("Dominio.Entidades.Opcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapituloDestinoId")
                        .HasColumnType("int");

                    b.Property<int?>("CapituloIntermedioId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CapituloDestinoId");

                    b.HasIndex("CapituloIntermedioId");

                    b.ToTable("Opciones");
                });

            modelBuilder.Entity("Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Dominio.Entidades.CapituloFinal", b =>
                {
                    b.HasBaseType("Dominio.Entidades.Capitulo");

                    b.Property<int>("ContadorAlcances")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("CapituloFinal");
                });

            modelBuilder.Entity("Dominio.Entidades.CapituloIntermedio", b =>
                {
                    b.HasBaseType("Dominio.Entidades.Capitulo");

                    b.HasDiscriminator().HasValue("CapituloIntermedio");
                });

            modelBuilder.Entity("Dominio.Entidades.Auditoria", b =>
                {
                    b.HasOne("Dominio.Entidades.Usuario", "Administrador")
                        .WithMany()
                        .HasForeignKey("AdministradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Capitulo", "Capitulo")
                        .WithMany()
                        .HasForeignKey("CapituloId");

                    b.HasOne("Dominio.Entidades.Historia", "Historia")
                        .WithMany()
                        .HasForeignKey("HistoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrador");

                    b.Navigation("Capitulo");

                    b.Navigation("Historia");
                });

            modelBuilder.Entity("Dominio.Entidades.Capitulo", b =>
                {
                    b.HasOne("Dominio.Entidades.Historia", null)
                        .WithMany("Capitulos")
                        .HasForeignKey("HistoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Entidades.Categoria", b =>
                {
                    b.HasOne("Dominio.Entidades.Historia", null)
                        .WithMany("Categorias")
                        .HasForeignKey("HistoriaId");
                });

            modelBuilder.Entity("Dominio.Entidades.Historia", b =>
                {
                    b.HasOne("Dominio.Entidades.CapituloIntermedio", "CapituloInicial")
                        .WithMany()
                        .HasForeignKey("CapituloInicialId1");

                    b.Navigation("CapituloInicial");
                });

            modelBuilder.Entity("Dominio.Entidades.Lectura", b =>
                {
                    b.HasOne("Dominio.Entidades.CapituloFinal", "FinalAlcanzado")
                        .WithMany()
                        .HasForeignKey("FinalAlcanzadoId");

                    b.HasOne("Dominio.Entidades.Historia", "Historia")
                        .WithMany()
                        .HasForeignKey("HistoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinalAlcanzado");

                    b.Navigation("Historia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dominio.Entidades.Opcion", b =>
                {
                    b.HasOne("Dominio.Entidades.Capitulo", "CapituloDestino")
                        .WithMany()
                        .HasForeignKey("CapituloDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.CapituloIntermedio", null)
                        .WithMany("Opciones")
                        .HasForeignKey("CapituloIntermedioId");

                    b.Navigation("CapituloDestino");
                });

            modelBuilder.Entity("Dominio.Entidades.Usuario", b =>
                {
                    b.OwnsOne("Dominio.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Dominio.ValueObjects.Password", "Password", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Entidades.Historia", b =>
                {
                    b.Navigation("Capitulos");

                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("Dominio.Entidades.CapituloIntermedio", b =>
                {
                    b.Navigation("Opciones");
                });
#pragma warning restore 612, 618
        }
    }
}
